import "ExplorerItem.idl";
import "RegExShortcut.idl";

namespace PowerRenameUI_new
{
    [default_interface]
    runtimeclass MainWindow : Windows.UI.Xaml.Controls.UserControl
    {
        MainWindow();
        Windows.Foundation.Collections.IObservableVector<ExplorerItem> ExplorerItems { get; };
        Windows.Foundation.Collections.IObservableVector<RegExShortcut> SearchRegExShortcuts { get; };
        Windows.Foundation.Collections.IObservableVector<RegExShortcut> FileRegExShortcuts { get; };

        void AddExplorerItem(Int32 id, String original, Int32 type, Int32 parentId);
    }
}
